namespace VideoTranslation.Api.Models;

/// <summary>
/// Result from the multi-agent validation pipeline.
/// Contains aggregated results from all specialist agents.
/// </summary>
public class MultiAgentValidationResult
{
    /// <summary>
    /// Whether the validation passed overall (based on weighted score >= threshold).
    /// </summary>
    public bool IsValid { get; set; }

    /// <summary>
    /// Weighted average score from all agents (0-100).
    /// Weights: Translation 40%, Technical 30%, Cultural 30%
    /// </summary>
    public double OverallScore { get; set; }

    /// <summary>
    /// Final recommendation based on score thresholds.
    /// - "Approve" if score >= 80
    /// - "NeedsReview" if score 50-79
    /// - "Reject" if score < 50
    /// Note: All jobs still require human approval regardless of recommendation.
    /// </summary>
    public string Recommendation { get; set; } = "NeedsReview";

    /// <summary>
    /// Human-readable summary of the validation results.
    /// Generated by the orchestrator agent after aggregating specialist results.
    /// </summary>
    public string Summary { get; set; } = string.Empty;

    /// <summary>
    /// Results from the Translation Review Agent.
    /// Analyzes semantic accuracy, grammar, and fluency.
    /// </summary>
    public AgentReviewResult? TranslationReview { get; set; }

    /// <summary>
    /// Results from the Technical Review Agent.
    /// Analyzes timing, sync, formatting, and reading speed.
    /// </summary>
    public AgentReviewResult? TechnicalReview { get; set; }

    /// <summary>
    /// Results from the Cultural Review Agent.
    /// Analyzes cultural adaptation, idioms, and tone.
    /// </summary>
    public AgentReviewResult? CulturalReview { get; set; }

    /// <summary>
    /// Thread ID for the Orchestrator Agent.
    /// Use this for general questions about the validation.
    /// </summary>
    public string? OrchestratorThreadId { get; set; }

    /// <summary>
    /// Thread ID for the Translation Review Agent.
    /// Use this for detailed translation/grammar questions.
    /// </summary>
    public string? TranslationAgentThreadId { get; set; }

    /// <summary>
    /// Thread ID for the Technical Review Agent.
    /// Use this for timing/formatting questions.
    /// </summary>
    public string? TechnicalAgentThreadId { get; set; }

    /// <summary>
    /// Thread ID for the Cultural Review Agent.
    /// Use this for cultural adaptation questions.
    /// </summary>
    public string? CulturalAgentThreadId { get; set; }

    /// <summary>
    /// All issues found by all agents, merged and categorized.
    /// </summary>
    public List<MultiAgentIssue> AllIssues { get; set; } = new();

    /// <summary>
    /// When the validation was completed.
    /// </summary>
    public DateTime ValidatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Calculates the weighted overall score from individual agent scores.
    /// Weights: Translation 40%, Technical 30%, Cultural 30%
    /// </summary>
    public void CalculateOverallScore()
    {
        double translationScore = TranslationReview?.Score ?? 0;
        double technicalScore = TechnicalReview?.Score ?? 0;
        double culturalScore = CulturalReview?.Score ?? 0;

        // Weighted average: Translation 40%, Technical 30%, Cultural 30%
        OverallScore = (translationScore * 0.4) + (technicalScore * 0.3) + (culturalScore * 0.3);

        // Determine recommendation based on thresholds
        if (OverallScore >= 80)
        {
            Recommendation = "Approve";
            IsValid = true;
        }
        else if (OverallScore >= 50)
        {
            Recommendation = "NeedsReview";
            IsValid = true; // Still valid, just needs review
        }
        else
        {
            Recommendation = "Reject";
            IsValid = false;
        }
    }

    /// <summary>
    /// Merges issues from all agents into AllIssues list.
    /// </summary>
    public void MergeIssues()
    {
        AllIssues.Clear();
        
        if (TranslationReview?.Issues != null)
            AllIssues.AddRange(TranslationReview.Issues);
        
        if (TechnicalReview?.Issues != null)
            AllIssues.AddRange(TechnicalReview.Issues);
        
        if (CulturalReview?.Issues != null)
            AllIssues.AddRange(CulturalReview.Issues);
    }
}

/// <summary>
/// Result from a single specialist agent's review.
/// </summary>
public class AgentReviewResult
{
    /// <summary>
    /// Name of the agent that performed this review.
    /// </summary>
    public string AgentName { get; set; } = string.Empty;

    /// <summary>
    /// Type of agent for routing purposes.
    /// Values: "translation", "technical", "cultural"
    /// </summary>
    public string AgentType { get; set; } = string.Empty;

    /// <summary>
    /// Score assigned by this agent (0-100).
    /// </summary>
    public double Score { get; set; }

    /// <summary>
    /// Detailed reasoning for the score.
    /// </summary>
    public string Reasoning { get; set; } = string.Empty;

    /// <summary>
    /// Issues found by this agent.
    /// </summary>
    public List<MultiAgentIssue> Issues { get; set; } = new();

    /// <summary>
    /// When this agent completed its review.
    /// </summary>
    public DateTime ReviewedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Thread ID for this agent (for follow-up chat).
    /// </summary>
    public string? ThreadId { get; set; }
}

/// <summary>
/// A specific issue found during multi-agent validation.
/// </summary>
public class MultiAgentIssue
{
    /// <summary>
    /// Severity level: "critical", "major", "minor", "suggestion"
    /// </summary>
    public string Severity { get; set; } = "minor";

    /// <summary>
    /// Category/source of the issue.
    /// Values: "translation", "technical", "cultural"
    /// </summary>
    public string Category { get; set; } = string.Empty;

    /// <summary>
    /// Description of the issue.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Location in the subtitle file (cue number or timestamp).
    /// </summary>
    public string? Location { get; set; }

    /// <summary>
    /// Suggested fix for the issue.
    /// </summary>
    public string? Suggestion { get; set; }
}
